mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'repository', '2.0.2', :github_tarball => 'boxen/puppet-respository'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
